apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  tolerations:
  - key: "COLOR"
    operator: "Equal"
    value: "RED"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: red
            operator: In
            values: [""]
  containers:
    - name: red-whale
      image: bitops/tinywhale
