name: Publish new version of image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push the image
      run: |
        docker login -u bitops -p "{{ secrets.DOCKERHUB_PASSWORD }}"

        TAG=$(date +%s)
        docker build -t "bitops/tiny-whale:$TAG" .
        docker push "bitops/tiny-whale:$TAG"
