name: Build and tag new version of image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the image
      run: |
        docker build -t bitops/tiny-whale:$(date +%s) .
