name: Build and tag new version of image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: bitops
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: bitops/tinywhale
        tag_with_ref: true
        tag_with_sha: true
