name: Build and tag new version of image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GITHASH: ${{ github.sha }
      with:
        name: bitops/tinywhale
        username: bitops
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        buildargs: GITHASH
